spring.application.name=SistemaClubeSoft
# Porta em que a aplicação Spring Boot será executada.
server.port=8080
# Cuidado com caracteres especiais na senha, como '#', etc.
# Quando usar o pooler de conexões, incluir o parâmetro 'prepareThreshold=0' para evitar problemas de preparação de consultas.
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.ifsowqolhzesxxeodemb&password=IgorCezar205&prepareThreshold=0
# Esquema de criação do banco de dados: 'create' para criar as tabelas a cada execução, 'update' para atualizar o esquema.
spring.jpa.hibernate.ddl-auto=update
# Exibe as consultas SQL no console para depuração.
spring.jpa.show-sql=true
# Define o dialeto do Hibernate para PostgreSQL, garantindo compatibilidade com as funcionalidades específicas do banco de dados.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
